config/routes.rb
Rails.application.routes.draw do
  resources :homes
  root to: 'books#homes'
  get 'books/new'
  get 'books' => 'books#index', as: 'index_book'
  get 'books/:id' => 'books#show', as: 'show_book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  post 'books' => 'books#create'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :Title, presence: true
  validates :Body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    # Viewへ渡すためのインスタンス変数に空のモデルオブジェクトを生成する。
    @book = Book.new
  end

  def index
    @book = Book.new
    @book = Book.all
  end
    
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "successfully create"
      redirect_to books_path
    else
      flash.now[:alert] = "create error"
      render :index
    end
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "successfully update"
      redirect_to books_path
    else
      flash.now[:alert] = "update error"
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_path  # 投稿一覧画面へリダイレクト
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:Title, :Body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :Title %>
  <h4>Body</h4>
  <%= f.text_area :Body %>
  <%= f.submit 'Update Book' %>
  <%= link_to "Edit", edit_book_path(@book.id) %>
  <%= link_to "Back", index_book_path(@book.id) %>

<% end %>

app/views/books/homes.html.erb
<body>
  <h1>
    "ようこそ"
    <strong>Bookers</strong>  
    "へ！"</h1>
  <p>
    <strong>Bookers</strong>
    "では、さまざまな書籍に関するあなたの意見や"
  </p>
  <p>
    "印象を共有し交換することができます"
  </p>
  <p>
    <%= link_to "start", index_book_path %>
  </p>

</body>

app/views/books/index.html.erb
<h3>Books</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
    </tr>
  </thead>

<tbody>
<% Book.all.each do |book| %>
  <tr> 
    <td>
      <%= book.Title %>
    </td>
    <td>
      <%= book.Body %>
    </td>
    <td>
      <%= link_to "show", show_book_path(book.id) %>
      <%= link_to "edit", edit_book_path(book.id) %>
      <%= link_to "destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
    </td>
  </tr>  
<% end %>

</tbody>   
</table>

<h3>New book</h3>
<!-- form_for部分 -->
<%= form_with model: @book, url:'/books', local:true do |f| %>

  <h4>Title</h4>
    <%= f.text_field :Title %>

  <h4>Body</h4>
    <%= f.text_area :Body %>

  <br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>hoppend error
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<!-- form_with部分 -->
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<h2>Title</h2>
<p><%= @book.Title %></p>
<h2>Body</h2>
<p><%= @book.Body %></p>
<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", index_book_path(@book.id) %>

app/views/homes/index.html.erb
<body>
  <h1>
    "ようこそ"
    <strong>Bookers</strong>  
    "へ！"</h1>
  <p>
    <strong>Bookers</strong>
    "では、さまざまな書籍に関するあなたの意見や"
  </p>
  <p>
    "印象を共有し交換することができます"
  </p>
  <p>
    <%= link_to "start", book_path(@book.id) %>
  </p>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <body>
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
  </body>

<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>